[package]
name = "black-jack"
version = "0.0.16-a"
authors = ["Miles Granger <miles59923@gmail.com>"]
description = "DataFrame / Series processing in Rust - Work in progress"
repository = "https://github.com/milesgranger/black-jack"
readme = "README.md"
license-file = "LICENSE"

[badges]
travis-ci = { repository = "https://github.com/milesgranger/black-jack", branch = "master" }
coveralls = { repository = "https://github.com/milesgranger/black-jack", branch = "master", service = "github" }

[lib]
name = "blackjack"

[dependencies]
num = "^0.2"
csv = "^1.0"
streaming-stats = "^0.2"
GSL = "^1.0"
rayon = "^1.0"
itertools = "^0.7"
flate2 = { version = "^1.0", features = ["rust_backend"], default-features = false }
prettytable-rs = "^0.8"
indexmap = "^1.0"
ndarray = "^0.12.1"
derive_more = "^0.13.0"
bincode = "1.0.1"
serde_derive = "^1.0.27"
serde = "^1.0.80"
failure = "^0.1"
snap = "0.2"

[features]
default = ["GSL/v2"]

[dev-dependencies]
float-cmp = "0.4.0"
criterion = "0.2"

[[bench]]
name = "bench_marks"
harness = false